apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-infrastructure-roles
data:
  batman: |
    name: batman
    inrole: [role1, role2]
    user_flags:
      - superuser
      - login
    db_parameters:
      log_statement: all
  robin: |
    name: robin
    inrole:
      - postgres
